// Service implementation for the Slack Cosmo Connect plugin.
//
// SlackService maps the gRPC contract generated from src/schema.graphql
// (by `wgc router plugin generate`) onto the Slack Web API via the
// slackclient.Client interface.
//
// Conventions:
//   - "not found" (channel/user the bot cannot see) maps to a nil result,
//     not an error — that is the GraphQL convention for nullable queries.
//   - List queries return an empty list on not-found.
//   - Any other Slack/API error is returned as a gRPC error.
//   - Optional scalar arguments arrive as protobuf wrappers
//     (google.protobuf.Int32Value / StringValue); nil means "absent" and
//     the schema default applies.
package main

import (
	"context"
	"errors"
	"fmt"

	service "github.com/wundergraph/cosmo/plugin/generated"
	slackclient "github.com/wundergraph/cosmo/plugin/src/slackclient"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

// SlackService implements the generated gRPC server interface.
type SlackService struct {
	service.UnimplementedSlackServiceServer

	slack slackclient.Client
}

// NewSlackService builds a SlackService backed by the given Slack client.
func NewSlackService(c slackclient.Client) *SlackService {
	return &SlackService{slack: c}
}

// QuerySlackChannel implements the slackChannel(id: ID!) GraphQL query.
func (s *SlackService) QuerySlackChannel(
	ctx context.Context,
	req *service.QuerySlackChannelRequest,
) (*service.QuerySlackChannelResponse, error) {
	ch, err := s.slack.GetChannel(ctx, req.GetId())
	if err != nil {
		if errors.Is(err, slackclient.ErrNotFound) {
			return &service.QuerySlackChannelResponse{}, nil
		}
		return nil, fmt.Errorf("slackChannel: %w", err)
	}

	return &service.QuerySlackChannelResponse{
		SlackChannel: toProtoChannel(ch),
	}, nil
}

// QuerySlackMessages implements slackMessages(channelId: ID!, limit: Int = 50).
func (s *SlackService) QuerySlackMessages(
	ctx context.Context,
	req *service.QuerySlackMessagesRequest,
) (*service.QuerySlackMessagesResponse, error) {
	limit := 50
	if l := req.GetLimit(); l != nil {
		limit = int(l.GetValue())
	}

	msgs, err := s.slack.GetMessages(ctx, req.GetChannelId(), limit)
	if err != nil {
		if errors.Is(err, slackclient.ErrNotFound) {
			return &service.QuerySlackMessagesResponse{SlackMessages: nil}, nil
		}
		return nil, fmt.Errorf("slackMessages: %w", err)
	}

	return &service.QuerySlackMessagesResponse{
		SlackMessages: toProtoMessages(msgs),
	}, nil
}

// QuerySlackThread implements slackThread(channelId: ID!, threadTs: String!).
func (s *SlackService) QuerySlackThread(
	ctx context.Context,
	req *service.QuerySlackThreadRequest,
) (*service.QuerySlackThreadResponse, error) {
	msgs, err := s.slack.GetThread(ctx, req.GetChannelId(), req.GetThreadTs())
	if err != nil {
		if errors.Is(err, slackclient.ErrNotFound) {
			return &service.QuerySlackThreadResponse{SlackThread: nil}, nil
		}
		return nil, fmt.Errorf("slackThread: %w", err)
	}

	return &service.QuerySlackThreadResponse{
		SlackThread: toProtoMessages(msgs),
	}, nil
}

// QuerySlackUser implements slackUser(id: ID!).
func (s *SlackService) QuerySlackUser(
	ctx context.Context,
	req *service.QuerySlackUserRequest,
) (*service.QuerySlackUserResponse, error) {
	u, err := s.slack.GetUser(ctx, req.GetId())
	if err != nil {
		if errors.Is(err, slackclient.ErrNotFound) {
			return &service.QuerySlackUserResponse{}, nil
		}
		return nil, fmt.Errorf("slackUser: %w", err)
	}

	return &service.QuerySlackUserResponse{
		SlackUser: toProtoUser(u),
	}, nil
}

// ----- Type conversion helpers -----
//
// These translate between the domain types from the slackclient package and
// the protobuf types generated by wgc. Optional (nullable) GraphQL fields
// map to protobuf wrapper types: an empty domain value becomes a nil wrapper
// so the router renders the field as null instead of an empty string.

func strPtr(v string) *wrapperspb.StringValue {
	if v == "" {
		return nil
	}
	return wrapperspb.String(v)
}

func int32Ptr(v int) *wrapperspb.Int32Value {
	if v == 0 {
		return nil
	}
	return wrapperspb.Int32(int32(v))
}

func toProtoChannel(c *slackclient.Channel) *service.SlackChannel {
	return &service.SlackChannel{
		Id:          c.ID,
		Name:        c.Name,
		Topic:       strPtr(c.Topic),
		Purpose:     strPtr(c.Purpose),
		MemberCount: int32Ptr(c.MemberCount),
		IsPrivate:   c.IsPrivate,
	}
}

func toProtoMessage(m slackclient.Message) *service.SlackMessage {
	return &service.SlackMessage{
		ChannelId: m.ChannelID,
		Ts:        m.TS,
		UserId:    m.UserID,
		Text:      m.Text,
		ThreadTs:  strPtr(m.ThreadTS),
		Permalink: strPtr(m.Permalink),
	}
}

func toProtoMessages(msgs []slackclient.Message) []*service.SlackMessage {
	out := make([]*service.SlackMessage, 0, len(msgs))
	for _, m := range msgs {
		out = append(out, toProtoMessage(m))
	}
	return out
}

func toProtoUser(u *slackclient.User) *service.SlackUser {
	return &service.SlackUser{
		Id:       u.ID,
		Name:     u.Name,
		RealName: strPtr(u.RealName),
		Email:    strPtr(u.Email),
		IsBot:    u.IsBot,
	}
}
